export const trucks = [
  {
    id: '1',
    title: 'Mercedes Benz Actros',
    year: 2019,
    location: 'Buenos Aires',
    price: '12.800.000',
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Mercedes-Benz_Actros_1845_IMG_0130.jpg',
  },
  {
    id: '2',
    title: 'Iveco Stralis',
    year: 2018,
    location: 'Córdoba',
    price: '10.500.000',
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Iveco_Stralis_2013_%28front%29.JPG',
  },
  {
    id: '3',
    title: 'Scania R500',
    year: 2020,
    location: 'Santa Fe',
    price: '14.200.000',
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Scania_R500_6x4.jpg',
  },
  {
    id: '4',
    title: 'Volvo FH16',
    year: 2017,
    location: 'Mendoza',
    price: '11.700.000',
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Volvo_FH_540_Truck.jpg',
  },
  {
    id: '5',
    title: 'Ford Cargo 2042',
    year: 2015,
    location: 'Neuquén',
    price: '9.800.000',
    image: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Ford_Cargo_2042.jpg',
  },
  {
    id: '6',
    title: 'MAN TGX',
    year: 2021,
    location: 'La Pampa',
    price: '15.300.000',
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/MAN_TGX_Euro_6.jpg',
  },
];
